#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : multiprocess
Version  : 0.70.12.2
Release  : 3
URL      : https://github.com/uqfoundation/multiprocess/releases/download/multiprocess-0.70.12.2/multiprocess-0.70.12.2.tar.gz
Source0  : https://github.com/uqfoundation/multiprocess/releases/download/multiprocess-0.70.12.2/multiprocess-0.70.12.2.tar.gz
Summary  : better multiprocessing and multithreading in python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: multiprocess-license = %{version}-%{release}
Requires: multiprocess-python = %{version}-%{release}
Requires: multiprocess-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(dill)
BuildRequires : pypi(py)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
multiprocess
============
better multiprocessing and multithreading in python
About Multiprocess
------------------
``multiprocess`` is a fork of ``multiprocessing``, and is developed as part of ``pathos``: https://github.com/uqfoundation/pathos

%package license
Summary: license components for the multiprocess package.
Group: Default

%description license
license components for the multiprocess package.


%package python
Summary: python components for the multiprocess package.
Group: Default
Requires: multiprocess-python3 = %{version}-%{release}

%description python
python components for the multiprocess package.


%package python3
Summary: python3 components for the multiprocess package.
Group: Default
Requires: python3-core
Provides: pypi(multiprocess)
Requires: pypi(dill)

%description python3
python3 components for the multiprocess package.


%prep
%setup -q -n multiprocess-0.70.12.2
cd %{_builddir}/multiprocess-0.70.12.2

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1644188765
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 setup.py build

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
PYTHONPATH=%{buildroot}$(python -c "import sys; print(sys.path[-1])") python setup.py test
%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/multiprocess
cp %{_builddir}/multiprocess-0.70.12.2/LICENSE %{buildroot}/usr/share/package-licenses/multiprocess/60bf9a94881bd37fc8faf68090e1db85965fcdf1
python3 -tt setup.py build  install --root=%{buildroot}
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/multiprocess/60bf9a94881bd37fc8faf68090e1db85965fcdf1

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
