#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : multiprocess
Version  : 0.70.13
Release  : 7
URL      : https://github.com/uqfoundation/multiprocess/releases/download/multiprocess-0.70.13/multiprocess-0.70.13.tar.gz
Source0  : https://github.com/uqfoundation/multiprocess/releases/download/multiprocess-0.70.13/multiprocess-0.70.13.tar.gz
Summary  : better multiprocessing and multithreading in python
Group    : Development/Tools
License  : BSD-3-Clause
Requires: multiprocess-license = %{version}-%{release}
Requires: multiprocess-python = %{version}-%{release}
Requires: multiprocess-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(dill)
BuildRequires : pypi(py)
BuildRequires : pypi(setuptools)
BuildRequires : pypi-pluggy
BuildRequires : pypi-pytest
BuildRequires : pypi-tox
BuildRequires : pypi-virtualenv

%description
multiprocess
============
better multiprocessing and multithreading in python
About Multiprocess
------------------
``multiprocess`` is a fork of ``multiprocessing``. ``multiprocess`` extends ``multiprocessing`` to provide enhanced serialization, using `dill`. ``multiprocess`` leverages ``multiprocessing`` to support the spawning of processes using the API of the python standard library's ``threading`` module. ``multiprocessing`` has been distributed as part of the standard library since python 2.6.

%package license
Summary: license components for the multiprocess package.
Group: Default

%description license
license components for the multiprocess package.


%package python
Summary: python components for the multiprocess package.
Group: Default
Requires: multiprocess-python3 = %{version}-%{release}

%description python
python components for the multiprocess package.


%package python3
Summary: python3 components for the multiprocess package.
Group: Default
Requires: python3-core
Provides: pypi(multiprocess)
Requires: pypi(dill)

%description python3
python3 components for the multiprocess package.


%prep
%setup -q -n multiprocess-0.70.13
cd %{_builddir}/multiprocess-0.70.13
pushd ..
cp -a multiprocess-0.70.13 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1656433696
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx"
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 -msse2avx "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/multiprocess
cp %{_builddir}/multiprocess-0.70.13/LICENSE %{buildroot}/usr/share/package-licenses/multiprocess/69368483de737879eeee980c021b7048730cf102
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/multiprocess/69368483de737879eeee980c021b7048730cf102

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
